### PR TITLE
Implement look_at_direction

### PR DESCRIPTION
**Pull request by Rayman**
I needed a method to look with the head of the robot in a general direction. @reinzor what do you think of it?

### CODE REVIEW

**Comment by reinzor** [comment]
Look at direction is not really defined since it is not related to a frame.
Or why is it logical to just take the base frame link?

-Rein

**Comment by Rayman** [comment]
Well, if it's a horizontal frame that moves with the robot, then it works. We could also use a neck frame but I dont know how they're oriented in sergio.

If direction is large enough (>10m or something), the robot will look in that general direction. For example 30 degrees to the right.

**Comment by reinzor** [comment]
​For me this is a little bit to vague. ​

-Rein

**Comment by LoyVanBeek** [comment]
Looking in a "general direction"  is indeed a bit vague. We could instead define a set of points to look at and look in the general direction of the points, e.g. the center of them of look at each of those one by one. That way, you can 'inspect' an area of volume.

**Pull request closed without merging**
